//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnSpaceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.AppointmentPersonPractices = new HashSet<AppointmentPersonPractice>();
            this.AppointmentPersonTests = new HashSet<AppointmentPersonTest>();
            this.AppointmentPractices = new HashSet<AppointmentPractice>();
            this.AppointmentTests = new HashSet<AppointmentTest>();
            this.PatientTestCollectionFeedbacks = new HashSet<PatientTestCollectionFeedback>();
            this.PersonIdentificationFeedbacks = new HashSet<PersonIdentificationFeedback>();
        }
    
        public int id { get; set; }
        public int userId { get; set; }
        public Nullable<int> testId { get; set; }
        public Nullable<int> pracId { get; set; }
        public int patientId { get; set; }
        public System.DateTime appointmentDate { get; set; }
        public System.DateTime nextAppointDate { get; set; }
        public string feedback { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentPersonPractice> AppointmentPersonPractices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentPersonTest> AppointmentPersonTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentPractice> AppointmentPractices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTest> AppointmentTests { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientTestCollectionFeedback> PatientTestCollectionFeedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonIdentificationFeedback> PersonIdentificationFeedbacks { get; set; }
        public virtual Practice Practice { get; set; }
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
