//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnSpaceApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class slowlearnerDataBaseEntities : DbContext
    {
        public slowlearnerDataBaseEntities()
            : base("name=slowlearnerDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AppointmentPersonPractice> AppointmentPersonPractices { get; set; }
        public virtual DbSet<AppointmentPersonTest> AppointmentPersonTests { get; set; }
        public virtual DbSet<AppointmentPractice> AppointmentPractices { get; set; }
        public virtual DbSet<AppointmentTest> AppointmentTests { get; set; }
        public virtual DbSet<CaregiverPurposal> CaregiverPurposals { get; set; }
        public virtual DbSet<Collection> Collections { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PatientTestCollectionFeedback> PatientTestCollectionFeedbacks { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonIdentification> PersonIdentifications { get; set; }
        public virtual DbSet<PersonIdentificationFeedback> PersonIdentificationFeedbacks { get; set; }
        public virtual DbSet<PersonPicture> PersonPictures { get; set; }
        public virtual DbSet<PersonPracticCollection> PersonPracticCollections { get; set; }
        public virtual DbSet<PersonPractice> PersonPractices { get; set; }
        public virtual DbSet<PersonTest> PersonTests { get; set; }
        public virtual DbSet<PersonTestCollection> PersonTestCollections { get; set; }
        public virtual DbSet<Practice> Practices { get; set; }
        public virtual DbSet<PracticeCollection> PracticeCollections { get; set; }
        public virtual DbSet<Sentence> Sentences { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestCollection> TestCollections { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserPatient> UserPatients { get; set; }
    }
}
