//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnSpaceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientTestCollectionFeedback
    {
        public int id { get; set; }
        public int patientId { get; set; }
        public int testCollectionId { get; set; }
        public int collectionId { get; set; }
        public bool feedback { get; set; }
        public Nullable<int> AppointmentId { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Collection Collection { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual TestCollection TestCollection { get; set; }
    }
}
