//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnSpaceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPractice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonPractice()
        {
            this.AppointmentPersonPractices = new HashSet<AppointmentPersonPractice>();
            this.PersonPracticCollections = new HashSet<PersonPracticCollection>();
        }
    
        public int id { get; set; }
        public Nullable<int> patientId { get; set; }
        public Nullable<int> createdBy { get; set; }
        public string title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentPersonPractice> AppointmentPersonPractices { get; set; }
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonPracticCollection> PersonPracticCollections { get; set; }
        public virtual User User { get; set; }
    }
}
